hipache:
    container_name: cuplatform_hipache
    image: tutum/hipache:0.3.1
    ports:
        - "80:80"
    links:
        - redis:redis
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro

redis:
    container_name: cuplatform_redis
    image: redis:3.0.1
    command: redis-server --appendonly yes
    ports:
        - 6379:6379
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro

mysql:
    container_name: cuplatform_mysql
    image: mysql:5.7.4
    environment:
        - MYSQL_ROOT_PASSWORD=changeit
        - MYSQL_DATABASE=cloudunit
    ports:
        - 3306:3306
    volumes_from:
        - mysqldata
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro

mysqldata:
    container_name: cuplatform_mysqldata
    image: ubuntu:14.04 
    volumes: 
        - /var/lib/mysql 
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro   

testmysql:
    container_name: cuplatform_testmysql
    image: mysql:5.7.4
    environment:
        - MYSQL_ROOT_PASSWORD=changeit
        - MYSQL_DATABASE=cloudunit
    ports:
        - 3307:3306
    volumes_from:
        - testmysqldata
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro

testmysqldata:
    container_name: cuplatform_testmysqldata
    image: ubuntu:14.04
    volumes:
        - /var/lib/mysql
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro

dnsdock:
    container_name: cuplatform_dnsdock
    image: tonistiigi/dnsdock:v1.10.0
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
    ports:
       - "172.17.42.1:53:53/udp"
    command: -nameserver="8.8.8.8:53" -http=":80" -dns=":53" -verbose="true" -environment="cloud" -domain="unit"

cadvisor:
    container_name: cuplatform_cdavisor
    image: google/cadvisor:0.14.0
    environment:
        - DB_USER=root
        - DB_PASS=root
        - DB_NAME=cadvisor
    ports:
        - 8081:8080
    volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker:/var/lib/docker:ro
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
    command: --housekeeping_interval=5s

registry:
    container_name: cuplatform_registry
    image: registry:0.9.1
    ports:
        - "5000:5000"
    volumes:
        - /registry:/registry
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
    environment:
        - STORAGE_PATH=/registry
        - GUNICORN_OPTS=["--preload"]

